### ISSUE TITLE
Drag to ScrollPane, if zoomed out, should be possible 

### ISSUE THREAD

**Issue by arognar** [corlab/ComponentViewTest#20]

**Comment by xwavex** [comment]
@arognar  Hat das was mit der Implementierung von David zutun? Wer macht das?

**Comment by arognar** [comment]
@xwavex es geht darum, dass der ScrollPane den ganzen MPSCanvas skaliert und wenn man dann zu weit rauszoomt oder den canvas verschiebt , hat man Flächen außerhalb auf denen der drop nicht mehr funktioniert.  Probiere morgen ob ich den drop einfach ohne probleme auf getParent absetzen kann.

**Comment by xwavex** [comment]
ok super!

Am Do., 12. Okt. 2017, 09:24 schrieb Julian Seidelmann <
notifications@github.com>:
